routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsuarioController;
use App\Http\Controllers\SistemaController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\FunController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InicioController;
use App\Http\Controllers\AsignacionController;
use App\Http\Controllers\AccesosController;
use App\Http\Controllers\Auth\TwoFactorController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('welcome');


Route::get('/', function () {
    return view('auth.login');
    
});

Route::get('verify/resend', [TwoFactorController::class, 'resend'])->name('verify.resend');
Route::resource('verify', TwoFactorController::class)->only(['index', 'store']);

Auth::routes();

//Route::resource('/usuario',UsuarioController::class);

Route::group(['middleware' => ['auth', 'twofactor']], function () {
   
    Route::resource('/sistema',SistemaController::class);

    Route::post('irasistema',[SistemaController::class, 'irasistema']);

    Route::resource('/rol',MenuController::class);

    Route::resource('/crearSistema',SistemaController::class);

    Route::resource('/editRol',MenuController::class);

    Route::resource('/permiso',FunController::class);

    Route::resource('/usuario',UsuarioController::class);

    Route::resource('/editPermiso',FunController::class);

    Route::resource('/cliente',ClienteController::class);

    Route::resource('/inicio',InicioController::class);

    Route::resource('/asignacion',AsignacionController::class);

    Route::resource('/accesos',AccesosController::class);

    

});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Accesos') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>


                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/principal.blade.php
@extends('layouts.app')
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>ACCESOS</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
      

    </head>
    <body class="antialiased">



<div class="jumbotron ">
          <h1>SISTEMA DE GESTIÓN DE CONTROL DE ACCESOS</h1>
          <h2>Bienvenido</h2>
        </div>

        @if(Session::has('sistema_creado'))
        <div class="alert alert-success">
        <strong>Éxito!</strong> 
        
        {{session('sistema_creado')}}
        
        </div>
        @endif

        @if(Session::has('sistema_duplicado'))
        <div class="alert alert-danger">
        <strong>Error!</strong> 
        
        {{session('sistema_duplicado')}}
        
        </div>
      @endif

        <div class="container">
            <div class="row justify-content-center">

            
              <form class="col-md-8" action="/irasistema" method="POST">
              @csrf                 
                      <div class="form-group ">
                        <label for="sel1">Seleccione un sistema a gestionar:</label>

                        <select class="form-control" name="sis">
                          @foreach($sistemas as $sistema)
                            <option value = '{{ $sistema->COD_SISTEMA }}' >{{$sistema->NOM_SISTEMA}}</option>
                          @endforeach

                        </select>
                      </div>
                      <button type="submit" class="btn btn-success">
                      Ingresar
                      </button>
                      
                      <a class="btn btn-info" href="{{route('sistema.create')}}">Nuevo</a>

       </form>
       

     </div>
      </div>


    </body>
</html>